services:
  - docker:dind

stages:
    - pre_test
    - test
    - build

lint:
 image: node:12.16
 stage: pre_test
 script:
    - npm install
    - npm run lint

test:
 image: node:12.16
 stage: test
 script:
    - npm install
    - npm test

build:
 image: docker:latest
 stage: build
 only:
    - branches
 except:
    - master
 script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - >
       sed -i 's/git-commit-hash/'${CI_COMMIT_SHA}'/' package.json
     - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg NPMRC_CONTENT="$NPMRC_CONTENT" .
     - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

push:
 image: docker:latest
 stage: build
 only:
     - master
 script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - >
       sed -i 's/git-commit-hash/'${CI_COMMIT_SHA}'/' package.json
     - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg NPMRC_CONTENT="$NPMRC_CONTENT" .
     - docker push ${CI_REGISTRY_IMAGE}:latest
     - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
