services:
  - docker:dind

stages:
    - pre_test
    - build

test:
 image: node:9-alpine
 stage: pre_test
 script:
    - echo -e "$NPMRC_CONTENT" > ~/.npmrc
    - apk --update add git alpine-sdk python python-dev
    - npm install
    - npm run lint

lint:
 image: node:9-alpine
 stage: pre_test
 script:
    - echo -e "$NPMRC_CONTENT" > ~/.npmrc
    - apk --update add git alpine-sdk python python-dev
    - npm install
    - npm test

build:
 image: docker:latest
 stage: build
 only:
    - branches
 except:
    - master
 script:
     - docker build --tag ${CI_REGISTRY_IMAGE}:latest .

push:
 image: docker:latest
 stage: build
 only:
     - master
 script:
     - docker pull $CONTAINER_IMAGE:latest || true
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
     - docker push ${CI_REGISTRY_IMAGE}:latest
