image: docker:stable
services:
  - docker:dind
before_script:
  - apk update
  - apk add nodejs-npm expect
  - export IMAGE_NAME=lympo/microservice-skeleton
  - npm config set registry https://$NPM_URL
  - |
      /usr/bin/expect <<EOD
      spawn npm adduser
      expect {
          "Username:" {send "$NPM_USERNAME\r"; exp_continue}
          "Password:" {send "$NPM_PASSWORD\r"; exp_continue}
          "Email: (this IS public)" {send "$NPM_EMAIL\r"; exp_continue}
      }
      EOD

stages:
  - pre_test
  - deploy
  - post_test

docker_build:
  stage: pre_test
  only:
    refs:
      - branches
  script:
    - docker build -f Dockerfile -t $IMAGE_NAME:latest --build-arg NPMRC_CONTENT="$(cat ~/.npmrc)" .

# thats example of deploy if you are building shared lib
# npm_publish:
#   stage: deploy
#   only:
#     - master
#   script:
#     - npm install publish
#     - npm publish

# example of acceptance testing
# npm_install_version:
#     stage: post_test
#     only:
#       - master
#     script:
#       - apk add jq
#       - export NPM_PKG_VER=`cat package.json | jq -r .version`
#       - cd /tmp
#       - npm install lympo-mainstore@$NPM_PKG_VER
# npm_install_latest:
#     stage: post_test
#     only:
#       - master
#     script:
#       - cd /tmp
#       - npm install lympo-mainstore
