version: '3.5'
services:
  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: "development" # To install nodemon and other dev stuff
        NPMRC_CONTENT: "//registry.npmjs.org/:_authToken=your_token_for_private_packages"
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: "development" # To start nodemon, enable dev.env, stacktraces and scope bypass
      DEV_BYPASS_SCOPES: "discounts:write.all" # To debug wo having to do authentication, only for DEV
      DEV_ENFORCE_TOKEN_PAYLOAD: "{\"scope\": \"discounts:write.all\" }" # Thats for handlers checking token payload, only for DEV
    env_file:
      - ./dev.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/logs # Consider redirecting to /tmp:... if you have permission issues when writing to logs on linux
  mongodb:
    image: mongo:5.0
    # Uncomment to initiate replica set, if you know cleaner way to do this - please suggest
    # healthcheck:
    #     test: echo 'rs.initiate();cfg=rs.conf();cfg.members[0].host="mongodb:27017";rs.reconfig(cfg,{force:true})' | mongo --quiet || echo ok
    #     start_period: 15s
    #     timeout: 60s
    #     retries: 1
    # command: --replSet "rs0" --bind_ip localhost,mongodb,127.0.0.1
