version: '2.1'
services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
    environment:
          - ELASTIC_SEARCH_HOST=http://elastic:9200
    depends_on:
      store:
        condition: service_started
      elasticsearch:
        condition: service_healthy
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
      container_name: elastic
      environment:
        - http.host=0.0.0.0
        - transport.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      volumes:
        - ./esdata:/usr/share/elasticsearch/data
  #      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - 9200:9200
        - 9300:9300
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      mem_limit: 2g
      cap_add:
        - IPC_LOCK
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
  store:
    image: lympo/main-store:master
    container_name: store

volumes:
  esdata:
    driver: local