version: '2'
services:
  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - lympo-main-store
    environment:
      - MONGODB_URL=mongodb://lympo-main-store/{dbName}
      - ENV_FILE=dev.env
    volumes:
      - .:/app
      - /app/node_modules
  lympo-main-store:
    image: lympo/main-store:master
